# Generated by Django 4.1 on 2023-11-21 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='model',
            old_name='mark_id',
            new_name='mark',
        ),
    ]
